- calibration/ADCPTG/A00234__20160701.csv
added new cal sheet with new values
> added new cal sheet

- test/unit/test_cruise.py
This should highlight two issues with the current cruise csv file, one bad time and one duplicate row.
> Added unit tests for CruiseInformation.csv

- bulk/platform_bulk_load-AssetRecord.csv
- cruise/CruiseInformation.csv
Added Pioneer 8 info to the cruise information sheet
Added Pioneer 8 platform information
> Added Pioneer 8 cruise information

- calibration/FLORTM/CGINS-FLORTM-03130__20161021.csv
- calibration/FLORTM/CGINS-FLORTM-03185__20160913.csv
- calibration/FLORTM/CGINS-FLORTM-03884__20160914.csv
- calibration/FLORTM/CGINS-FLORTM-04465__20160818.csv
- calibration/PARADM/CGINS-PARADM-50146__20160922.csv
- calibration/PARADM/CGINS-PARADM-50153__20161019.csv
- calibration/PARADM/CGINS-PARADM-50236__20160930.csv
- calibration/PARADM/CGINS-PARADM-50244__20160926.csv
- calibration/PCO2WB/CGINS-PCO2WB-C0112__20170523.csv
- calibration/PCO2WB/CGINS-PCO2WB-C0113__20170523.csv
Added Pioneer 8 glider sensor cal sheets
Added PCO2W-B cal sheets
> Added cal sheets for Pioneer 8 glider sensors and new PCO2W cal sheets

- bulk/platform_bulk_load-AssetRecord.csv
- cruise/CruiseInformation.csv
Updated Cruise Information sheet:
Added Irminger 4
Added Southern Ocean 4
Added Argentine Basin 4
Updated Platform Bulk Load sheet:
Added Irminger 4 platform info
Argentine Basin 4 and Southern Ocean 4 are recovery cruises only
> Updated global cruise information

- calibration/PCO2WA/ATAPL-58336-00009__20170117.csv
> update to PC02WA calibration sheet following vendor info

- bulk/platform_bulk_load-AssetRecord.csv
- bulk/platform_vocab.csv
Added CP01CNPM (Coastal Pioneer Central Profiler Mooring)
Added CP03ISPM (Coastal Pioneer Inshore Profiler Mooring)
> Added 2 new Pioneer platforms to Platform Vocab

- calibration/ADCPSL/CGINS-ADCPSL-22650__20170411.csv
- calibration/DOFSTK/CGINS-DOFSTK-00209__20170726.csv
- calibration/DOFSTK/CGINS-DOFSTK-02499__20170708.csv
- calibration/DOFSTK/CGINS-DOFSTK-02708__20170711.csv
- calibration/DOFSTK/CGINS-DOFSTK-02978__20170718.csv
- calibration/DOFSTK/CGINS-DOFSTK-03370__20170725.csv
- calibration/FLORTK/CGINS-FLORTK-00830__20170726.csv
- calibration/FLORTK/CGINS-FLORTK-01029__20170725.csv
- calibration/FLORTK/CGINS-FLORTK-01031__20170726.csv
- calibration/FLORTK/CGINS-FLORTK-01117__20170725.csv
- calibration/FLORTK/CGINS-FLORTK-01466__20170725.csv
- calibration/PARADK/CGINS-PARADK-20437__20170717.csv
- calibration/PARADK/CGINS-PARADK-20447__20170717.csv
- calibration/PARADK/CGINS-PARADK-20464__20170717.csv
- calibration/PARADK/CGINS-PARADK-20513__20170717.csv
- calibration/PARADK/CGINS-PARADK-20525__20170717.csv
Added new sensor cal sheets for Pioneer 9 profiler moorings
> Pioneer 9 profiler mooring sensor cal sheets

- bulk/platform_bulk_load-AssetRecord.csv
- cruise/CruiseInformation.csv
Added P10 moorings to platform_bulk_load sheet
Added P10 cruise to CruiseInformation sheet
> Updates for Pioneer 10

- calibration/CTDAVN/CGINS-CTDAVN-00424__20171009.csv
- calibration/CTDAVN/CGINS-CTDAVN-00425__20171009.csv
- calibration/DOSTAN/CGINS-DOSTAN-02901__20171113.csv
- calibration/DOSTAN/CGINS-DOSTAN-02909__20171113.csv
Updated CTD and DOSTA cal sheets
> Updated AUV cal sheets

- vocab/vocab.version
- vocab/vocab_csv_ingest.py
Simply bringing over vocab files from the uframe-ooi repository to here.
> Issue #13584 - Move vocab scripts to asset-management repo

- vocab/vocab.csv
Added reference designators for 2 NOC sensors and second PCO2A
> Added CUSTARD ref des to vocab.csv

- calibration/PARADM/CGINS-PARADM-50164__20130304.csv
- calibration/PARADM/CGINS-PARADM-50164__20140420.csv
- calibration/PARADM/CGINS-PARADM-50164__20150404.csv
- calibration/PARADM/CGINS-PARADM-50164__20151011.csv
@cwingard Can you review and merge so that this goes into the next release?
Thanks
> Changed PAR calibration to correct CE deployments 386-1, 2, and 3

- tools/load/README.md
Updated the readme file to include instructions for adding deployments for new instruments in test.
> Included instructions for test updates

- README.md
change travis URL to use oceanobservatories repo instead of ooi-integration
> one line change to README.md

- bulk/eng_bulk_load-AssetRecord.csv
- bulk/platform_bulk_load-AssetRecord.csv
- bulk/sensor_bulk_load-AssetRecord.csv
- cruise/CruiseInformation.csv
Endurance 14 additions to:
sensor_bulk (OPTAA-D 344)
eng_bulk
platform bulk
cruise.csv
> Endurance 14 crossMIO

- calibration/DOSTAJ/CGINS-DOSTAJ-00353__20230112.csv
> dosta 353 cal

- bulk/eng_bulk_load-AssetRecord.csv
- bulk/sensor_bulk_load-AssetRecord.csv
- calibration/DOFSTK/CGINS-DOFSTK-04361__20230120.csv
- calibration/FLORTK/CGINS-FLORTK-01602__20221101.csv
- calibration/PARADK/CGINS-PARADK-20555__20221129.csv
ce09ospm instrument calibrations:
dofst, flort, parad
> E18cals_WFP

- cruise/CruiseInformation.csv
This pull request although needed is a chance to teach how a pull request works to @jwhitefield42
> updates arrival date and time for Endurance cruise 18

- bulk/sensor_bulk_load-AssetRecord.csv
It had already been on RDB and Vault since 2020.
> Add FLORT-K 1705 to GHAM for OSU WFP.

- calibration/PCO2WB/CGINS-PCO2WB-C0063__20230801.csv
- calibration/PCO2WB/CGINS-PCO2WB-C0082__20230620.csv
- calibration/PCO2WB/CGINS-PCO2WB-C0084__20230720.csv
- calibration/PCO2WB/CGINS-PCO2WB-C0089__20230807.csv
- calibration/PCO2WB/CGINS-PCO2WB-C0119__20230801.csv
- calibration/PCO2WB/CGINS-PCO2WB-C0126__20230720.csv
Final PCO2W cals for EA Fall 2023 deployment. All files up on Alfresco. Files will be loaded to Vault by WHOI next week.
> PCO2W Cals

- vocab/vocab.csv
Added instrument number to TRHPH TOC Level 4
> Updated TRHPH names

- calibration/FLORTJ/CGINS-FLORTJ-01084__20240425.csv
- calibration/FLORTJ/CGINS-FLORTJ-01208__20230920.csv
> CSPP FLORT-J Calibrations

- calibration/PARADJ/CGINS-PARADJ-00365__20240307.csv
- calibration/PARADJ/CGINS-PARADJ-00407__20231025.csv
- calibration/PARADJ/CGINS-PARADJ-00437__20231025.csv
- calibration/PARADJ/CGINS-PARADJ-00505__20231220.csv
> CSPP PARAD-J Calibrations

- calibration/DOSTAJ/CGINS-DOSTAJ-00209__20231025.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00308__20140115.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00308__20231025.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00350__20160313.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00350__20180323.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00350__20230920.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00351__20160313.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00351__20230920.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00352__20221213.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00353__20231214.csv
All check files are on alfresco.
> DOSTA-J calibration updates

- calibration/DOSTAD/CGINS-DOSTAD-00134__20241122.csv
- calibration/DOSTAD/CGINS-DOSTAD-00136__20241114.csv
- calibration/DOSTAD/CGINS-DOSTAD-00218__20241114.csv
- calibration/DOSTAD/CGINS-DOSTAD-00220__20241114.csv
- calibration/DOSTAD/CGINS-DOSTAD-00291__20241122.csv
- calibration/DOSTAD/CGINS-DOSTAD-00313__20241115.csv
- calibration/DOSTAD/CGINS-DOSTAD-00315__20241115.csv
- calibration/DOSTAD/CGINS-DOSTAD-00478__20241115.csv
- calibration/DOSTAD/CGINS-DOSTAD-00479__20241121.csv
- calibration/DOSTAD/CGINS-DOSTAD-00482__20241121.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00209__20241120.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00350__20241121.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00351__20241120.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00352__20241119.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00353__20241119.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00646__20241119.csv
- calibration/DOSTAJ/CGINS-DOSTAJ-00672__20241120.csv
Calibration certificates are on alfresco (in the DOSTA folder in the Calibration and Repair branch) and all contain "2-point_Winkler" in the corresponding filenames.
> DOSTA-D,J 2pt Winkler Calibration Updates
